# Generated by Django 5.2.4 on 2025-08-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_casedata_log_time_alter_casedata_case_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedata',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
